In [15]:
from flowstab.temporal_network import ContTempNetwork, ContTempInstNetwork

In [16]:
source_nodes=[0, 1, 1]
target_nodes=[1, 2, 3]
starting_times=[0, 1, 2]
ending_times=[2.5, 2.5, 2.5]
cont_net=ContTempNetwork(source_nodes=source_nodes, target_nodes=target_nodes, starting_times=starting_times, ending_times=ending_times)

In [17]:
A = cont_net.compute_static_adjacency_matrix(start_time=0, end_time=1.5)
A.todense()

matrix([[0. , 1.5, 0. , 0. ],
        [1.5, 0. , 0.5, 0. ],
        [0. , 0.5, 0. , 0. ],
        [0. , 0. , 0. , 0. ]])

In [18]:
A = cont_net.compute_static_adjacency_matrix()
A.todense()

matrix([[0. , 2.5, 0. , 0. ],
        [2.5, 0. , 1.5, 0.5],
        [0. , 1.5, 0. , 0. ],
        [0. , 0.5, 0. , 0. ]])

In [19]:
cont_net.node_array

array([0, 1, 2, 3])

In [20]:
cont_net.events_table

,source_nodes,target_nodes,starting_times,ending_times,durations
0,0,1,0,2.5,2.5
1,1,2,1,2.5,1.5
2,1,3,2,2.5,0.5


In [21]:
cont_net._compute_time_grid()

In [22]:
cont_net.time_grid.index.get_level_values(0).unique().to_numpy()

array([0. , 1. , 2. , 2.5])

In [9]:
import numpy as np

In [23]:
cont_net.times

Index([0.0, 1.0, 2.0, 2.5], dtype='float64', name='times')

In [11]:
int(np.where(cont_net.times == 0)[0])

TypeError: only 0-dimensional arrays can be converted to Python scalars

In [ ]:
cont_net._get_closest_time(t=1.5)

TypeError: only 0-dimensional arrays can be converted to Python scalars